// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://lusuraonlijbjnvxihzt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx1c3VyYW9ubGlqYmpudnhpaHp0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI4ODc4NzgsImV4cCI6MjA4ODQ2Mzg3OH0.AcYIkCApogw7YgO-oWQbkFDA9J9BGlbpFwJ3tvSjtBQ";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);